### ISSUE TITLE
Sentry Logger [warn]: Sentry responded with status code 403 to sent event.

### ISSUE THREAD

**Issue by lucaspossam** [ericjeker/nestjs-sentry-example#2]
Hi,

I just setup a new nest application and using your code I getting the following error:
![Screen Shot 2022-10-26 at 16 10 48](https://user-images.githubusercontent.com/62621488/198115786-31a7d5f7-3d64-4009-a3d9-78d8fcb59d7c.png)

I belive that is and update error since you're using version 6 and I'm installed version 7.16.

I'm new in Nest so the only thing I can do is scream for help kkkkk

Could you help me?

**Comment by ericjeker** [comment]
Hi Lucas,

Really sorry, it's been a while I didn't check this repository. Did you solve this issue already?

I'll try to update it with the last version and see if something is broken.

**Comment by ericjeker** [comment]
Hi Lucas,

I updated the repository to Sentry 7.21 and haven't had any issues with the setup. Let me know if you were able to solve your problem.
